import { ArrowRight, CircleHelp, ExternalLink, FileCheck2, Workflow } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Eyebrow } from '../components/Shared';

export function VerificationPage() {
  return <div className="verification-page"><div className="page-intro page-intro--short"><Eyebrow index="04 /">VERIFICATION</Eyebrow><div className="page-title-row"><div><h1>Check before you trust.</h1><p>The right questions matter as much as the outcome. Here is what a transparent recovery process should help you review.</p></div></div></div>
    <div className="verify-page-grid"><section className="verify-framework"><div className="workspace-panel-heading"><div><FileCheck2 size={19} strokeWidth={1.5} /><h3>A framework for independent review</h3></div><span>A PRACTICAL CHECKLIST</span></div><p className="framework-intro">Use these questions when assessing a recovery claim. They are prompts for your own review, not completed checks or a verified result.</p><div className="framework-list"><div><span className="framework-count">01</span><div><h4>Know the input.</h4><p>What information did you provide, and what should have remained on your device?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">02</span><div><h4>Understand the process.</h4><p>Which steps were actually taken, and which actions did you explicitly approve?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">03</span><div><h4>Check against a separate source.</h4><p>Can you validate relevant public information independently, without disclosing credentials?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">04</span><div><h4>Make the final call.</h4><p>Does the evidence support the outcome being presented? If not, pause and investigate.</p></div><CircleHelp size={19} /></div></div><div className="framework-note"><span>IMPORTANT</span> Screenshots, promises, and interface badges are not independent proof.</div></section>
      <aside className="verify-side"><div className="verify-side-dark"><span className="aside-overline">TRANSPARENCY / 01</span><h3>Know what happened.<br />Know what didn't.</h3><p>Verification is a user decision supported by evidence—not a decorative status indicator.</p></div><div className="verify-side-light"><Workflow size={21} strokeWidth={1.5} /><h4>Still defining the issue?</h4><p>Start with the guided walkthrough, then return to this checklist.</p><Link to="/app/recovery">Go to recovery <ArrowRight size={16} /></Link></div></aside>
    </div><div className="verification-bottom"><div><span>HAVE A QUESTION?</span><strong>Ask Trustos AI to explain verification.</strong></div><Link to="/app/assistant?prompt=verification">Ask Trustos AI <ExternalLink size={16} /></Link></div>
  </div>;
}
