import { ArrowRight, ArrowUpRight, Check, CircleHelp, ExternalLink, FileCheck2, SearchCheck, Workflow } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Eyebrow, PreviewTag } from '../components/Shared';
import { useAuth } from '../context/AuthContext';
import { useDemoActivity } from '../services/demoActivity';

export function VerificationPage() {
  const { user } = useAuth();
  const activity = useDemoActivity(user?.id || '');
  const hasDemo = activity.some((item) => item.event === 'completed');
  return <div className="verification-page"><div className="page-intro page-intro--short"><Eyebrow index="04 /">VERIFICATION</Eyebrow><div className="page-title-row"><div><h1>Check before you trust.</h1><p>The right questions matter as much as the outcome. Here is what a transparent recovery process should help you review.</p></div><PreviewTag>NO LIVE VERIFICATION</PreviewTag></div></div>
    <div className="verification-banner"><div className="verification-banner-icon"><SearchCheck size={25} strokeWidth={1.5} /></div><div><span>CURRENT STATUS</span><h2>There is no live result to verify.</h2><p>{hasDemo ? 'You completed a local walkthrough. That is a demonstration of the interface—not a recovered asset or verified transaction.' : 'Start a local walkthrough to explore the flow. Real recovery results and blockchain checks are not connected in this preview.'}</p></div><Link to="/app/recovery" className="btn btn-primary">{hasDemo ? 'Review the walkthrough' : 'Explore recovery'} <ArrowUpRight size={17} /></Link></div>
    <div className="verify-page-grid"><section className="verify-framework"><div className="workspace-panel-heading"><div><FileCheck2 size={19} strokeWidth={1.5} /><h3>A framework for independent review</h3></div><span>WHEN REAL RESULTS EXIST</span></div><p className="framework-intro">These are questions to ask when real functionality is available. The items below have <strong>not</strong> been checked by this preview.</p><div className="framework-list"><div><span className="framework-count">01</span><div><h4>Know the input.</h4><p>What information did you provide, and what should have remained on your device?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">02</span><div><h4>Understand the process.</h4><p>Which steps were actually taken, and which actions did you explicitly approve?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">03</span><div><h4>Check against a separate source.</h4><p>Can you validate relevant public information independently, without disclosing credentials?</p></div><CircleHelp size={19} /></div><div><span className="framework-count">04</span><div><h4>Make the final call.</h4><p>Does the evidence support the outcome being presented? If not, pause and investigate.</p></div><CircleHelp size={19} /></div></div><div className="framework-note"><span>IMPORTANT</span> Screenshots, promises, and interface badges are not independent proof.</div></section>
      <aside className="verify-side"><div className="verify-side-dark"><span className="aside-overline">TRANSPARENCY / 01</span><h3>Know what happened.<br />Know what didn't.</h3><p>Verification is a user decision supported by evidence—not a decorative status indicator.</p><div className="verify-side-status"><span><Check size={15} /> Local walkthrough available</span><span><CircleHelp size={15} /> Blockchain checks unavailable</span><span><CircleHelp size={15} /> No real recovery result</span></div></div><div className="verify-side-light"><Workflow size={21} strokeWidth={1.5} /><h4>Still defining the issue?</h4><p>Start with the guided walkthrough, then return to this checklist.</p><Link to="/app/recovery">Go to recovery <ArrowRight size={16} /></Link></div></aside>
    </div><div className="verification-bottom"><div><span>HAVE A QUESTION?</span><strong>Ask the local guide to explain verification.</strong></div><Link to="/app/assistant?prompt=verification">Ask Trustos AI <ExternalLink size={16} /></Link></div>
  </div>;
}
